### ISSUE TITLE
Problem with saving the project in tutorial notebooks

### ISSUE THREAD

**Issue by ehsan-asali** [erdzeichen/KiMoPack#10]
Hi, 

when running the notebooks in 'Tutorial_Notebooks_for_local_use' folder, I get the following error when the code tries to save the project. Could you please help me solve the issue?

Here's the error I get:

---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
Input In [14], in <cell line: 2>()
      1 savename = filename+'_own'
----> 2 ta.Save_project(filename=savename,   # set save name
      3                 path='results')   # set name of save folder
      5 ta.Save_data(save_RAW=False,         # do not save pre-processed data
      6              save_Fit=True,          # save pre-processed and fitted data
      7              filename=savename,      # set save name
      8              path='results')

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\KiMoPack\plot_func.py:7343, in TA.Save_project(self, filename, path)
   7341 	df['vary']=df['vary'].astype(bool)
   7342 	df['expr']=df['expr'].apply(lambda x:'%s'%x)
-> 7343 	df.to_hdf(str(hdf5_name.resolve()), key=key, append=True, mode='r+', format='t')
   7344 else:
   7345 	data = self.__dict__[key]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py:2763, in NDFrame.to_hdf(self, path_or_buf, key, mode, complevel, complib, append, format, index, min_itemsize, nan_rep, dropna, data_columns, errors, encoding)
   2759 from pandas.io import pytables
   2761 # Argument 3 to "to_hdf" has incompatible type "NDFrame"; expected
   2762 # "Union[DataFrame, Series]" [arg-type]
-> 2763 pytables.to_hdf(
   2764     path_or_buf,
   2765     key,
   2766     self,  # type: ignore[arg-type]
   2767     mode=mode,
   2768     complevel=complevel,
   2769     complib=complib,
   2770     append=append,
   2771     format=format,
   2772     index=index,
   2773     min_itemsize=min_itemsize,
   2774     nan_rep=nan_rep,
   2775     dropna=dropna,
   2776     data_columns=data_columns,
   2777     errors=errors,
   2778     encoding=encoding,
   2779 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\pytables.py:311, in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, format, index, min_itemsize, nan_rep, dropna, data_columns, errors, encoding)
    309 path_or_buf = stringify_path(path_or_buf)
    310 if isinstance(path_or_buf, str):
--> 311     with HDFStore(
    312         path_or_buf, mode=mode, complevel=complevel, complib=complib
    313     ) as store:
    314         f(store)
    315 else:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\pytables.py:591, in HDFStore.__init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    589 self._fletcher32 = fletcher32
    590 self._filters = None
--> 591 self.open(mode=mode, **kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\pytables.py:740, in HDFStore.open(self, mode, **kwargs)
    734     msg = (
    735         "Cannot open HDF5 file, which is already opened, "
    736         "even in read-only mode."
    737     )
    738     raise ValueError(msg)
--> 740 self._handle = tables.open_file(self._path, self._mode, **kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tables\file.py:300, in open_file(filename, mode, title, root_uep, filters, **kwargs)
    295             raise ValueError(
    296                 "The file '%s' is already opened.  Please "
    297                 "close it before reopening in write mode." % filename)
    299 # Finally, create the File instance, and return it
--> 300 return File(filename, mode, title, root_uep, filters, **kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tables\file.py:750, in File.__init__(self, filename, mode, title, root_uep, filters, **kwargs)
    747 self.params = params
    749 # Now, it is time to initialize the File extension
--> 750 self._g_new(filename, mode, **params)
    752 # Check filters and set PyTables format version for new files.
    753 new = self._v_new

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tables\hdf5extension.pyx:486, in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "C:\ci\hdf5_1611496732392\work\src\H5F.c", line 793, in H5Fopen
    unable to open file
  File "C:\ci\hdf5_1611496732392\work\src\H5VLcallback.c", line 3500, in H5VL_file_open
    open failed
  File "C:\ci\hdf5_1611496732392\work\src\H5VLcallback.c", line 3465, in H5VL__file_open
    open failed
  File "C:\ci\hdf5_1611496732392\work\src\H5VLnative_file.c", line 100, in H5VL__native_file_open
    unable to open file
  File "C:\ci\hdf5_1611496732392\work\src\H5Fint.c", line 1707, in H5F_open
    unable to read superblock
  File "C:\ci\hdf5_1611496732392\work\src\H5Fsuper.c", line 406, in H5F__super_read
    unable to locate file signature
  File "C:\ci\hdf5_1611496732392\work\src\H5FDint.c", line 123, in H5FD_locate_signature
    unable to read file signature
  File "C:\ci\hdf5_1611496732392\work\src\H5FDint.c", line 198, in H5FD_read
    driver read request failed
  File "C:\ci\hdf5_1611496732392\work\src\H5FDsec2.c", line 725, in H5FD_sec2_read
    file read failed: time = Fri Oct 21 16:20:48 2022
, filename = 'G:\Kimopack\KiMoPack\Tutorial_Notebooks_for_local_use\Data\Fitting-2\results\TA_Ru-dppz_400nm_ACN_own.hdf5', file descriptor = 8, errno = 13, error message = 'Permission denied', buf = 000000C0867E75A0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0

End of HDF5 error back trace

Unable to open/create file 'G:\Kimopack\KiMoPack\Tutorial_Notebooks_for_local_use\Data\Fitting-2\results\TA_Ru-dppz_400nm_ACN_own.hdf5'

**Comment by erdzeichen** [comment]
hej, I checked and everything works fine for me. There is however a suspicious comment in the error that mentions "Permissions denied" that looks like you do not have write access to the file where you are running things. Can this be? Since you are running on window could you please copy your working folder into you document folder and try it there.
