### ISSUE TITLE
Make a version without qt

### ISSUE THREAD

**Issue by erdzeichen** [erdzeichen/KiMoPack#12]

**Comment by aureliano-tm** [comment]
Is it possible to use plotly rather than matplotlib in qt for visualizing?
The former is more suitable for saving plot in jupyter notebook and keeping interactive.

**Comment by erdzeichen** [comment]
Hej, in principle yes, but as a general version this would be to much work as all theplot commands are different. I'm using mainly the plot command that is attached to pandas (pandas.DataFrame.plot()) and this works only with matplotlib. 
But to tell the truth I never had problems with the qt version staying interactive. Do you?

**Comment by erdzeichen** [comment]
I forgot to mention, I'm working on a real GUI version of the whole, where the plotting is completely done by tk.

**Comment by aureliano-tm** [comment]
Hi,
Thanks for your timely reply and selfless share.
No, I don't have this problem. It's just a little bit nettlesome to click a lot of figures in different windows. I prefer to save them using plotly in the Jupyter notebook and keep them interactive for exploring data.
By the way, I found the fitted kinetics is not entirely continuous. It seems changed when I change time interval in the raw data. Do you have any solutions?
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/271f40ee-50e7-4859-a0db-8bf4f4d0cd26)
Best Regards,
Min

**Comment by erdzeichen** [comment]
Mmmh, this is weired and can actually not happen. Can you check if this is the same in the ta.re['c'] please. (this are the concentration matrix)
What you want to achieve with the plotting you should be able to do by activating %matplotlib notebook I believe

**Comment by aureliano-tm** [comment]
I think it is really there, not for the parallel mode, but for the sequential and target model.
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/a86cafb1-a2f5-44db-aba8-18eed088c20d)
I would appreciate that if you could help me solving this problem. Thanks in advance.
[data.zip](https://github.com/erdzeichen/KiMoPack/files/12731492/data.zip)

**Comment by erdzeichen** [comment]
First I acknowledge it is there because you make a huge jump in the stepwidth. 
A cheat is that you can take the calculated c, adapt the values and then. 
ta.re=pf.fill_int(ds=ta.re['A'],c=corrected c)

I have played a while with making the simulation steps smoother (more substeps up to 1000) but this was not enough. I have to think about this a bit more how to make a robust solution, but I am going to raise an issue for this and will fix it,

I just discovered a bug or better a conceptional problem in the total numbers. If you cut the time then the peak does not get sampled properly and the total intensity is weired. 

Second comment, it is very dangerous to leave anything that you do not fit in the data so this is much better:
ta.mod = "exponential"
ta.par = lmfit.Parameters()
ta.par.add("k0", value=1 / 400, vary=True)
ta.par.add("t0", value=0, min=-1, max=1, vary=False)
ta.par.add("resolution", value=0.2, min=0, max=1, vary=False)
ta.par.add("infinite")
ta.par.add("background")
ta.timelimits = [0.4, 8000]
ta.Fit_Global()

**Comment by erdzeichen** [comment]
Ok Issue is solved upgrade to 7.2.17 and use ta.Fit_Global(fit_chirp=False,sub_sample=10)
This is not yet documented, but this will sub-sample the simulation and thus create a smoother modelling. You went a bit early to 100ps steps. I recomment to take a smoother transfer, maybe log steps?

**Comment by aureliano-tm** [comment]
Thanks for your timely help and I found the fitted concentration becomes smooth.

I admit there is still big improvement on my data collection and your suggestion is accepted.

Here I have some suggestion on the KiMoPack, wish you could consider:
1. There is no args to set the linear range (lintresh) in ta.Plot_RAW(scale_type="symlog), which is very useful for the first glance of data. I prefer to set lintresh=100 with timelimits = [-5, 8000] to make a clear inspect of the data from -5 to 100 ps without wasting too much space to display the data before time zero.
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/548afa48-9035-4d56-920c-54ec77c9dc2a)
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/d054c630-a80e-4c3b-a137-6fe221568daa)
2. ta.Plot_Interactive() is a really good idea to visualise the TA data in an interactive interface. But I feel it still couldn't replace the general software such as Surface Xplorer, which could scan each time delay or wavelength and save the spectra or kinetics in the figure. Maybe it is too hard to achieve in Python?
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/8caecded-3f14-4824-85b1-8ecab341b310)
3. When I use the target model to fit the data, it shows too much information about the decreased error, which I think it is meaningless. It blocked the fit results I concerned.
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/724971c4-6df8-4049-b5ee-3b26ab1a432d)
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/ab655e3f-9bf5-4c4a-b9a5-5ca7a7a10cc1)
By the way, it might be better to add the unit for rate. (It is really good to determine the rate using time ta.par.add("k0", value=1 / 438, vary=True))
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/0ccea00c-bbd4-43ad-8a89-ea34a34e4ed4)
4. I found that if I run the ta.Plot_fit_output(), it will create an empty folder named "result_figures" even though I don't need these figures.
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/5dcc4281-8e77-49bf-a81b-f9747b0b920c)
5. I couldn't load the .hdf5 file in TA_Advanced_Fit.ipynb. Do you have any idea?
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/d6f5ceef-1573-4f16-ab9b-6099a51e210c)
6. The unit of IRF is ps, it is a little bit confused when it is sorted with rate.
![image](https://github.com/erdzeichen/KiMoPack/assets/64117368/1d8a0666-ecaa-4c08-841e-2a5f031ee66c)
7. Is it better to save the raw kinetics (spectra) with the fitted kinetics (spectra) together (in two columns, many kinetics in a file)? It's more convenient to redraw the fitted result. 
8. Considering the time used for single fitting, is it possible to use server to run these python code for multiple fitting?

**Comment by aureliano-tm** [comment]
By the way, something I suggested might be wrong or based on my poor understanding.
Really thanks for sharing such useful tool and it's quite helpful to my research.

**Comment by erdzeichen** [comment]
Oi this is a loong answer. First, 7.3.0 does contain
ta.par.add('substeps',value=2)
where you speed up the fit.

Anyways. Answer 1: you can always use the plotting functions directly (with a lot more options) 

pf.plot1d, pf.plot2d or pf.plot_time

there is also the direct access to the raw plotting:
pf.plot_raw(ds = None, plotting = range(4), title = None, intensity_range = 1e-2, baseunit = 'ps',
			timelimits = None, scattercut = None, bordercut = None, wave_nm_bin = None, width = 10,
			rel_wave = np.arange(400, 900, 100), rel_time = [1, 5, 10], time_width_percent = 10,
			ignore_time_region = None, time_bin = None, cmap = None, color_offset = 0, 
			log_scale = True, plot_type = 'symlog', lintresh = 0.3, times = None, 
			save_figures_to_folder = False, savetype = 'png', path = None, filename = None, 
			print_click_position = False, data_type = 'differential Absorption in $\mathregular{\Delta OD}$',
			plot_second_as_energy = True, units = 'nm', return_plots = False, equal_energy_bin = None)
Which pretty much has all the options one might like. This is outside of the object. 

2. I am working on a jupyter version of surface explorer, will soon be done
3. yeah, this is the poblem of visual studio. you can always print eh output manual with ta.Print_Results() or hack the plot_func and comment line 4302
4.Should be suppressed now
5. yes this is your installation. The pytables is needed to read hdf5. Please install with "pip install tables"
6. Yes, but this does not make much sense to convert.  Hint, I recomment to use infinite instead of a large number. Much cleaner
7. True, but then I need to check if they are there ;o) Trick: use compare_at_wave, there you can generate the plot and then save the returned values
8. Yes! I am working on a parallel version (hard to make because these general functions can not be pickled. However I simply start multiple servers and test different models. That worked for me. I am working on a sleeker version, but often this performance comes at the price of versatility. (plus I'm a scientist not a coder ;o))

Nice that it is useful and keep pushing your ideas. For the future could you please simply make a new issue, then it is easier to track what I fix. 
(and don't forget to cite me ;o))

**Comment by aureliano-tm** [comment]
Thank you so much. You will find the citation in following article.

**Comment by aureliano-tm** [comment]
Thanks for your remind. I'm using this function.
