### ISSUE TITLE
Possibility of exporting DAS data

### ISSUE THREAD

**Issue by luccablois** [erdzeichen/KiMoPack#25]
Hello
I really enjoyed learning to fit my transient data on KiMoPack

I was wondering it it was possible to export the Decay Associated Spectra as .txt or .csv files so that i can put them on my thesis in the same standard as my other figures

Best wishes,
Lucca

**Comment by erdzeichen** [comment]
Hey Lucca,
ta.Save_data() called after fitting dumps everything into ascii files. You can also change all graphs in python. Linewidth, ranges, axis type and colors you give to the plotting call. (Details are described under parameter on read the docs) And if you have Only one window open you can get with ax=plt.gca() a handle to the axis.
Alternatively if you have qt you can change everything in the gui
Best Jens

**Comment by erdzeichen** [comment]
Very useful is the new mini help. Whenever you have an TA object you can call it with ta() and get a help with the most important functions

**Comment by luccablois** [comment]
I managed to extract everything.
I would like to commend you for making this package available, it saved me a lot of trouble
Many thanks :D
