### ISSUE TITLE
Cutting out second wavelength area in the spectrum (e.g. second harmonic)

### ISSUE THREAD

**Issue by T3lPie** [erdzeichen/KiMoPack#29]
Hey folks,

I was just asking if it is possible to cut out a second wavelength area in the spectrum? For example you have already cut out the excitation wavelength at 380-400nm but also want to cut out the second harmonic at 780nm. Is it possible in the code to add that?

Cheers,
Lukas

**Comment by PhotonChemist** [comment]
Hey Lukas,

This is already possible, if I understood you right. If I remember correctly you just have to use list instead of intergers as argument, when using the scattercut function. For example:
 ta.scattercut([380,480],[770,790])

Best regards,
Louis

**Comment by erdzeichen** [comment]
Hey, that is correct, both the ignore time range and scattercut can be stacked. So give it a list of lists. Just make sure that it is always first smaller and then larger. I believe i check for that, but not sure how careful i was there. 
Best Jens
