### ISSUE TITLE
Issue when opening some single scans

### ISSUE THREAD

**Issue by AxlEriksson** [erdzeichen/KiMoPack#3]
Sometimes when I use Summarize_scans() I get this error. I'm not sure yet if there is an issue with the single scan files themselves or if it's a plot_func issue

Input:
#single scans
ta=pf.Summarize_scans(list_of_scans='gui',list_to_dump='single',fileending='SIA')

output:

some data bad, try filtering
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._convert_tokens()

TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\KiMoPack\plot_func.py in __read_ascii_data(self, sep, decimal, index_is_energy, transpose, sort_indexes, divide_times_by, shift_times_by, external_time, external_wave, correct_ascii_errors, data_type, units)
   4291                                 try:# try forced conversion
-> 4292                                         self.ds_ori=pandas.read_csv(check_folder(path=self.path,filename=self.filename), sep=sep, index_col=0, dtype = np.float64)
   4293                                 except:

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    609 
--> 610     return _read(filepath_or_buffer, kwds)
    611 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    467     with parser:
--> 468         return parser.read(nrows)
    469 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   1056         nrows = validate_integer("nrows", nrows)
-> 1057         index, columns, col_dict = self._engine.read(nrows)
   1058 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   2060         try:
-> 2061             data = self._reader.read(nrows)
   2062         except StopIteration:

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._convert_column_data()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._convert_tokens()

ValueError: could not convert string to float: '--21.47483648'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~\anaconda3\lib\site-packages\KiMoPack\plot_func.py in Summarize_scans(list_of_scans, path_to_scans, list_to_dump, window1, window2, save_name, fileending, filename_part, return_removed_list, sep, decimal, index_is_energy, transpose, sort_indexes, divide_times_by, shift_times_by, external_time, external_wave, return_ds_only, data_type, units)
    694                                 filename = listen[1]
--> 695 				list_of_projects.append(TA(filename = filename,path = path, sep = sep, decimal = decimal, 
    696                                                                                         index_is_energy = index_is_energy, transpose = transpose,

~\anaconda3\lib\site-packages\KiMoPack\plot_func.py in __init__(self, filename, path, sep, decimal, index_is_energy, transpose, sort_indexes, divide_times_by, shift_times_by, external_time, external_wave, data_type, units)
   4217                 else:#we read in raw data from sia File
-> 4218 			self.__read_ascii_data(sep = sep, decimal = decimal, index_is_energy = index_is_energy, 
   4219                                                                         transpose = transpose, sort_indexes = sort_indexes,

~\anaconda3\lib\site-packages\KiMoPack\plot_func.py in __read_ascii_data(self, sep, decimal, index_is_energy, transpose, sort_indexes, divide_times_by, shift_times_by, external_time, external_wave, correct_ascii_errors, data_type, units)
   4294                                         #try:
-> 4295                                         self.ds_ori=self.ds_ori.applymap(lambda x: re.sub('--', '-',x))
   4296                                         self.ds_ori=self.ds_ori.applymap(lambda x: re.sub(r'\.+', '.',x))

~\anaconda3\lib\site-packages\pandas\core\frame.py in applymap(self, func, na_action)
   7843 
-> 7844         return self.apply(infer).__finalize__(self, "applymap")
   7845 

~\anaconda3\lib\site-packages\pandas\core\frame.py in apply(self, func, axis, raw, result_type, args, **kwds)
   7767         )
-> 7768         return op.get_result()
   7769 

~\anaconda3\lib\site-packages\pandas\core\apply.py in get_result(self)
    184 
--> 185         return self.apply_standard()
    186 

~\anaconda3\lib\site-packages\pandas\core\apply.py in apply_standard(self)
    275     def apply_standard(self):
--> 276         results, res_index = self.apply_series_generator()
    277 

~\anaconda3\lib\site-packages\pandas\core\apply.py in apply_series_generator(self)
    289                 # ignore SettingWithCopy here in case the user mutates
--> 290                 results[i] = self.f(v)
    291                 if isinstance(results[i], ABCSeries):

~\anaconda3\lib\site-packages\pandas\core\frame.py in infer(x)
   7841                 return lib.map_infer(x, func, ignore_na=ignore_na)
-> 7842             return lib.map_infer(x.astype(object)._values, func, ignore_na=ignore_na)
   7843 

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

~\anaconda3\lib\site-packages\KiMoPack\plot_func.py in <lambda>(x)
   4294                                         #try:
-> 4295                                         self.ds_ori=self.ds_ori.applymap(lambda x: re.sub('--', '-',x))
   4296                                         self.ds_ori=self.ds_ori.applymap(lambda x: re.sub(r'\.+', '.',x))

~\anaconda3\lib\re.py in sub(pattern, repl, string, count, flags)
    209     a replacement string to be used."""
--> 210     return _compile(pattern, flags).sub(repl, string, count)
    211 

TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-a54bc3d7aef0> in <module>
      1 #single scans
----> 2 ta=pf.Summarize_scans(list_of_scans='gui',list_to_dump='single',fileending='SIA')#window1=[2,100,1000,1100],window2=[2,100,500,780])

~\anaconda3\lib\site-packages\KiMoPack\plot_func.py in Summarize_scans(list_of_scans, path_to_scans, list_to_dump, window1, window2, save_name, fileending, filename_part, return_removed_list, sep, decimal, index_is_energy, transpose, sort_indexes, divide_times_by, shift_times_by, external_time, external_wave, return_ds_only, data_type, units)
    705                         list_of_projects = np.transpose(np.array(list_of_projects),(1, 2, 0))
    706                 except:
--> 707                         raise ValueError('Sorry did not understand the project_list entry, use GUI_open to create one')
    708         else:
    709                 try:

ValueError: Sorry did not understand the project_list entry, use GUI_open to create one

**Comment by buerviper** [comment]
I am not sure why this was marked as completed without comment, but I just wanted to chime in: for me, this problem was solved after discovering that my scans folder contains invisible files. Maybe a relict of copying from Mac to another system, who knows.
In any case, the manual solution is to create a new folder and to select only the .SIA files. Then it works out of the box.

**Comment by erdzeichen** [comment]
> I am not sure why this was marked as completed without comment, but I just wanted to chime in: for me, this problem was solved after discovering that my scans folder contains invisible files. Maybe a relict of copying from Mac to another system, who knows.
> In any case, the manual solution is to create a new folder and to select only the .SIA files. Then it works out of the box. 

Hey, because I fixed the problem and axl sits in my office... this is true, the peoblem can arrise if the other files also have the shape ".SIA" or whatever the pattern was.  Using a part of the filename can also solve the problem. But i can agree MacOS does some funny things sometimes
