### ISSUE TITLE
ta.save_figures_to_folder=True does not work for ta.Plot_fit_output(plotting=2)

### ISSUE THREAD

**Issue by thom-42** [erdzeichen/KiMoPack#32]
Hi,
I have encountered a bug using Version 7.4.9.
While:
```python
ta.save_figures_to_folder=True
ta.Plot_fit_output()`
```
saves all plots to the folder "result figures". (Though, some plots (SEL, SUM) are missing the title.)
When the plotting keyword is set to plotting=2:
```python
ta.save_figures_to_folder=True
ta.Plot_fit_output(plotting=2)`
```
only the folder "result figures" is created but no figures are saved.

**Comment by erdzeichen** [comment]
Thank you.
uh I hadn\t used this switch for a long time. But completely correct the saving did not work if only a few plots are selected. I caught the errors in a try>except, silencing it. 
The title is true, fixed for single kinetics. in the "sum sum" plot it is intentionally added only as title of the legend in the middle plot (to save space). Hope that's ok
