### ISSUE TITLE
t0 shift in ta.mod='exponential' not working

### ISSUE THREAD

**Issue by thom-42** [erdzeichen/KiMoPack#33]
Hi,
I cannot get the t0 shift in ta.mod='exponential' to work.
The monoexponential fit of the triplet decay does not yield a satisfying result, because t0 is not fitted properly:
```python
ta.mod='exponential'

ta.par=lmfit.Parameters()
ta.par.add('k0',value=1/29.759, min=0, max=100, vary=True)
ta.par.add('t0',value=0  ,min=-10,max=10,vary=True)          
ta.par.add('resolution', value=1.6, min=0, max=10, vary=False)
ta.Fit_Global()

ta.Plot_fit_output(plotting=2, scale_type='lin')
```
![exponential_fit_not_working](https://github.com/user-attachments/assets/abe15069-671c-40e1-892c-a91ad66cd1cc)

Setting t0=0 manually looks good:

```python
ta.mod='exponential'

ta.par=lmfit.Parameters()
ta.par.add('k0',value=1/27.7, min=0, max=100, vary=False)
ta.par.add('t0',value=0  ,min=-10,max=10,vary=False)          
ta.par.add('resolution', value=1.6, min=0, max=10, vary=False)
ta.Fit_Global()

ta.Plot_fit_output(plotting=2,scale_type='lin')
```
![t0=0](https://github.com/user-attachments/assets/9bfd21ba-b54f-46a5-a81e-d5e523155583)

However, nothing changes when I set t0 to a negative value:
```python
ta.mod='exponential'

ta.par=lmfit.Parameters()
ta.par.add('k0',value=1/27.7, min=0, max=100, vary=False)
ta.par.add('t0',value=-10  ,min=-10,max=10,vary=False)          #set to to -10
ta.par.add('resolution', value=1.6, min=0, max=10, vary=False)
ta.Fit_Global()

ta.Plot_fit_output(plotting=2,scale_type='lin')
```
![t0=neg](https://github.com/user-attachments/assets/cdeb3e6c-cfb8-424c-bcf4-089603616010)

And when I set t0 to a positive value the decay curve becomes strange.
```python
ta.mod='exponential'

ta.par=lmfit.Parameters()
ta.par.add('k0',value=1/27.7, min=0, max=100, vary=False)
ta.par.add('t0',value=10  ,min=-10,max=10,vary=False)          #set to to 10
ta.par.add('resolution', value=1.6, min=0, max=10, vary=False)
ta.Fit_Global()

ta.Plot_fit_output(plotting=2,scale_type='lin')
```
![t0=pos](https://github.com/user-attachments/assets/18708c65-91af-4979-93cb-5c00268141e4)
(The kink is at 10 ms)

What am I doing wrong or is this a bug?
Your help is much appreciated.

I have attached the Example workbook and data:
[Example.zip](https://github.com/user-attachments/files/16707875/Example.zip)

**Comment by erdzeichen** [comment]
Thank you for this detailed report. Yes I never handed the t0 to the rise function (that is only used for this). Fixed in 7.6.5.

**Comment by erdzeichen** [comment]
in your example I would suggest to replace baseunit='ms' with baseunit="time in ms"

**Comment by erdzeichen** [comment]
Btw the decay was shifted,  so since many use ignore_time_region for ultrafast fitting i next noticed the missing shift in the rise. But again thanks for the careful documentation and sorry for this obvious miss
