### ISSUE TITLE
Exclude pump scatter only at early times

### ISSUE THREAD

**Issue by carolin-m** [erdzeichen/KiMoPack#5]
Is there a way to exclude scattered light from the pump pulses only at early times. Could we simply extend the scattercut option, to hand over either 4 values [wavelength1, wavelength2, time1, time2] and if the last two values are kept empty it uses the full time-range if not it employ the scattercut only on the defined temporal-spectral rectangle?

**Comment by erdzeichen** [comment]
Sorry, this I will not do. The scattercut is set up to handle multiple scatter cuts at the moment. This needs a lot of work internally, as I piecewise spline the interpolation. Doing this only for certain times will not be stable.
Anyhow there is a easy workaround. you can either write zeros or N/A over the region you want to cover. 
ta.ds.loc[start_time:end_time,start_wavelength:end_wavelength] = np.nan
would accomplish this the rest of the code can work with that.
